### ISSUE TITLE
SeqIO FASTA SeqFormat is incomplete

### ISSUE THREAD

**Issue by matthewwiese** [maize-genetics/BioKotlin#22]
Hi all, I hope everyone is doing well. I've encountered a minor bug.

The [SeqFormat FASTA extension list](https://github.com/maize-genetics/BioKotlin/blob/master/src/main/kotlin/biokotlin/seqIO/SeqIO.kt#L8-L11)  is incomplete. It expects `.fa` or `.fasta` whereas my reference from NCBI has an `.fna` extension, which I've seen before and is common enough to [be listed on Wikipedia](https://en.wikipedia.org/wiki/FASTA_format#Filename_extension).

This came to my attention when using PHG v2's `create-ranges` command:

```
phg create-ranges                                                           \
    --reference-file data/reference/GCF_002114115.1_ASM211411v1_genomic.fna \
    --gff data/reference/genomic.gff                                        \
    --boundary gene                                                         \
    --pad 500                                                               \
    --range-min-size 500                                                    \
    -o apple.bed
Exception in thread "main" java.lang.IllegalArgumentException: Unknown file type: data/reference/GCF_002114115.1_ASM211411v1_genomic.fna
	at biokotlin.seqIO.SeqIOKt.reader(SeqIO.kt:54)
	at biokotlin.seqIO.NucSeqIO.<init>(NucSeqIO.kt:8)
	at biokotlin.seqIO.NucSeqIO.<init>(NucSeqIO.kt:6)
	at net.maizegenetics.phgv2.cli.CreateRanges.run(CreateRanges.kt:339)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:292)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:41)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:457)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:454)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:474)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:481)
	at net.maizegenetics.phgv2.cli.PhgKt.main(Phg.kt:58)
```

The exception is trivially avoided after renaming the file extension, although I figured I ought to report this as others will likely encounter it too.

**Comment by tcasstevens** [comment]
Fixed by https://github.com/maize-genetics/BioKotlin/pull/32

**Comment by tcasstevens** [comment]
https://github.com/maize-genetics/BioKotlin/pull/32

**Comment by matthewwiese** [comment]
@tcasstevens Hi Terry - thanks for the fix, could this be added to PHGv2? I have the most recent release and it's still giving the same error:

```
phg create-ranges                                                           \
    --reference-file data/reference/GCF_003254395.2_Amel_HAv3.1_genomic.fna \
    --gff data/reference/genomic.gff                                        \
    --boundary gene                                                         \
    --pad 500                                                               \
    --range-min-size 500                                                    \
    -o bee.bed
Exception in thread "main" java.lang.IllegalArgumentException: Unknown file type: data/reference/GCF_003254395.2_Amel_HAv3.1_genomic.fna
	at biokotlin.seqIO.SeqIOKt.reader(SeqIO.kt:54)
	at biokotlin.seqIO.NucSeqIO.<init>(NucSeqIO.kt:8)
	at biokotlin.seqIO.NucSeqIO.<init>(NucSeqIO.kt:6)
	at net.maizegenetics.phgv2.cli.CreateRanges.run(CreateRanges.kt:339)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:279)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:292)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:41)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:457)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:454)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:474)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:481)
	at net.maizegenetics.phgv2.cli.PhgKt.main(Phg.kt:58)
```

Version 2.3.15.152

**Comment by zrm22** [comment]
@matthewwiese Hi Matt,  We will be updating PHGv2 soon with the newest biokotlin version.  We also included a pretty substantial MAFToGVCF update due to a major change to anchor wave 1.2.3.  On the PHG side we need to add in some backwards compatibility so legacy MAF files can be used.  If you want to keep an eye on the development, the branch this is being done on is [here](https://github.com/maize-genetics/phg_v2/tree/update-maf-to-gvcf)

**Comment by matthewwiese** [comment]
@zrm22 Bril! Thanks for the info Zack, I'll keep an eye out.

**Comment by zrm22** [comment]
Just a heads up v2.4 of the PHG is now in a prerelease state.  You can download this here: https://github.com/maize-genetics/phg_v2/releases/tag/2.4.0.154
